const data = {
  products: [
    {
      _id: '1',
      name: 'PC PORTABLE MSI MODERN',
      category: 'pc portable',
      image: '/images/p1.png',
      price: 2400,
      brand: 'MSI',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'PC PORTABLE ASUS S509JA',
      category: 'pc portable',
      image: '/images/p2.png',
      price: 1100,
      brand: 'ASUS',
      rating: 4.0,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'PC PORTABLE ACER ASPIRE',
      category: 'pc portable',
      image: '/images/p3.png',
      price: 2100,
      brand: 'ACER',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'PC PORTABLE MSI GAMING',
      category: 'MSI',
      image: '/images/p5.png',
      price: 2900,
      brand: 'pc portable',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'CASQUE COMPATIBLE BEATS ',
      category: 'casque',
      image: '/images/p6.png',
      price: 50,
      brand: 'BEATS',
      rating: 4500,
      numReviews: 15,
      description: 'high quality product',
    },
     {
      _id: '6',
      name: 'MSI CASQUE GAMING  ',
      category: 'casque',
      image: '/images/p7.png',
      price: 279,
      brand: 'MSI',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
   
  ],
};
export default data;
